# Generated by Django 5.1.6 on 2025-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_event_user_post_timestamp_post_user_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
